version: '3.5'

services:
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: ${TIMEZONE}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    container_name: umt-postgres-db
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  pgadmin:
    depends_on:
      - db
    image: dpage/pgadmin4
    restart: always
    container_name: pg-admin-panel
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - ${PGADMIN_PORT}:${PGADMIN_LISTEN_PORT}

  api:
      depends_on:
        - db
      build:
        context: .
        dockerfile: Dockerfile
      container_name: umt-nest-api
      env_file:
        - .env
      ports:
        - ${API_PORT}:${API_PORT}
      volumes:
        - ./src:/app/src
